language: node_js

sudo: false

node_js:
  - "0.12"

branches:
  only:
  - blog

before_install:
- openssl aes-256-cbc -K $encrypted_811c71e0400e_key -iv $encrypted_811c71e0400e_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp doc/ssh_config ~/.ssh/config
- git config --global user.name "yourname"
- git config --global user.email youremail
- git clone -b master git@github.com:yourname/yourrepo.git .deploy_git

install:
- npm install hexo-cli -g
- npm install
- npm install hexo-generator-feed --save
- npm install hexo-generator-sitemap --save
- npm install hexo-deployer-git --save

script:
- hexo clean
- hexo g
- hexo d