language: node_js
node_js:
- '0.12'
branches:
  only:
  - blog
before_install:
- openssl aes-256-cbc -K $encrypted_55310d269300_key -iv $encrypted_55310d269300_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp ssh_config ~/.ssh/config
- git config --global user.name yinjimmy
- git config --global user.email jimmy.yin5@gmail.com
#- git clone -b master git@github.com:yinjimmy/yinjimmy.github.io.git .deploy_git
install:
- npm install hexo-cli -g
- npm install
- npm install hexo-generator-feed --save
- npm install hexo-deployer-git --save
script:
- hexo clean
- hexo g
- hexo g
#- git config credential.helper "store --file=.git/credentials"
#- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- hexo d
#env:
#  global:
#    secure: dmdjsF52XEPlVM8KV16+DHjRvHF6qaZM6UEDoxdhywNAyiiuTcpWQLfkyvVPeKOzBE7nm0dWU/sPXsiC25IUg9MjvxJxloo55c3GIOnK5rAwe2L04SNaYgoVDZcGh7xQw0M7zCM4QWHSTCe3ZaMYlU88GETLnLjasTCvWwDtIHLtCTn2HyGxin3l8TN6x7SDmYZzRQZknHgjnkHByQ0DiD7VxBN0aeHnL45ZSWaFiOtBLfm2Wi9pf/YpIk4W1Fuq5vRwzucOJ0kpKPUGjPRI40TLW/Hz9WzFCE+Vgx9ZzDDcAgVV/QrO7/q4O0B42GEbX5m+Zc/9GLjxAQMbBKIQ1QyRi1seXa4g3i7tku5qESkX0p6Xuma6CEi5aNMUNm19M5wHxa2Smk1gOfLMJM5/ypxI0Cafk9rIzwHA1O3A9PkdHZTYSaqfNCQRLYyX/SGZrJW4pTMEkbK4IUXkXZJJ65fEX/Yzbj68+XQwv61yx/Dpbdv+ArZ6DHZwdl2dYEFeZCuhDsm3XL1jKIn0BgzKp2gOg9VogkMYNUkqOI1LHK5F20oWgdS4Py3EGdR4puiZjkYUt51jHUngaw181M1TR/dDaf8OhQSQiNQsYmmyBtfxaEoWvFbTnQjN4vNFSYuI0nsumJC9cbu6kdOKmsbP9IJsgQwwAxPURFG7BMHfgz8=
